server:
  port: 9002
spring:
  application:
    name: health_oms_backend
  # datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itcast_health_all?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1 # redis的主机ip
    port: 6379
#日志
logging:
  level:
    #生产环境一般使用info级别，开发和测试环境使用debug级别
    root: info
# mybatis
mybatis:
  mapper-locations: classpath:com/itheima/health/mapper/*.xml # mapper映射文件路径
  type-aliases-package: com.itheima.health.pojo
#分页插件
pagehelper:
  # 指定使用的数据库类型
  helperDialect: mysql
#七牛配置
qiniu:
  urlPrefix: http://rc5k3g7g2.hn-bkt.clouddn.com/
  accessKey: fhuiPBXFTZIgJdtZGuMtCUJ3zSrT7k3AHmVNE4UA
  secretKey: zKKxCW_HjQmwtl4JI80nMT0Ve2V7VZDbqT4zt_tT
  bucket: heima-health-389